service: Cassandra-User
provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-1
  memorySize: 1024
  timeout: 300
package:
  include:
    - app/**
    - libs/**
    - system/**
    - node_modules/**
    - Serverless.js
    - serverless.yml
  exclude:
    - Server.js
    - server.yaml
functions:
  app:
    handler: Serverless.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'