service: Cassandra-User
provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-1
  memorySize: 1024
  timeout: 300
package:
  include:
    - app/**
    - libs/**
    - system/**
    - node_modules/**
    - serverless.js
    - serverless.yml
  exclude:
    - tests/**
    - server.js
    - app.yaml
functions:
  app:
    handler: serverless.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'